services:
  coredns:
    image: coredns/coredns
    container_name: dns.${DOMAIN}
    restart: unless-stopped
    expose:
      - '53'
      - '53/udp'
    ports:
      - '53:53'
      - '53:53/udp'
    volumes:
      - './services/coredns:/etc/coredns'
    command: -conf /etc/coredns/Corefile
    networks:
      - backend

  proxy:
    image: nginxproxy/nginx-proxy:1.4
    container_name: proxy.${DOMAIN}
    restart: unless-stopped
    environment:
      - TRUST_DOWNSTREAM_PROXY=true
      - ENABLE_IPV6=false
      - DEFAULT_HOST=www.inabox.ies-sabadell.cat
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./services/proxy/certs:/etc/nginx/certs
      - ./services/proxy/vhost:/etc/nginx/vhost.d
      - ./services/proxy/html:/usr/share/nginx/html
      #- ./services/proxy/conf.d:/etc/nginx/conf.d
    ports:
      - '80:80'
      - '443:443'
    networks:
      - backend
      - frontend

#  proxy-acme:
#    image: nginxproxy/acme-companion
#    container_name: proxy-acme.${DOMAIN}
#    restart: always
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ./services/nginx/certs:/etc/nginx/certs 
#      - ./services/nginx/vhost:/etc/nginx/vhost.d
#      - ./services/nginx/html:/usr/share/nginx/html
#      - ./services/nginx/acme:/etc/acme.sh
#    environment:
#      - "DEFAULT_EMAIL=inabox@ies-sabadell.cat"
#      - NGINX_PROXY_CONTAINER=proxy.inabox.ies-sabadell.cat
#    depends_on:
#      proxy:
#        condition: service_started
#    networks:
#      - backend

  postgres:
    image: postgres
    container_name: postgres.${DOMAIN}
    restart: unless-stopped
    secrets:
      - db-password
    shm_size: 128mb
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
       test: [ "CMD", "pg_isready" ]
       interval: 10s
       timeout: 5s
       retries: 5
    networks:
      - backend

#  adminer:
#    image: adminer
#    container_name: adminer.${DOMAIN}
#    restart: unless-stopped
#    environment:
#      - ADMINER_DEFAULT_SERVER=postgres
#      - ADMINER_DESIGN=nette
#      - VIRTUAL_HOST=adminer.inabox.ies-sabadell.cat
#      - LETSENCRYPT_HOST=adminer.inabox.ies-sabadell.cat      
#    ports:
#      - 8081:8080
#    depends_on:
#      postgres:
#        condition: service_healthy
#    networks:
#      - backend

  redis:
    image: redis:5
    container_name: redis.${DOMAIN}
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - backend

  guacd:
    image: guacamole/guacd
    container_name: guacd.${DOMAIN}
    restart: unless-stopped
    environment:
      - GUACD_LOG_LEVEL=info
    ports:
      - 4822:4822
    networks:
      - backend

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole.${DOMAIN}
    restart: unless-stopped
    environment:
      - POSTGRESQL_HOSTNAME=postgres
      - POSTGRESQL_DATABASE=guacamole_db
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=development
      - POSTGRESQL_PORT=5432
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
      - VIRTUAL_HOST=guacamole.inabox.ies-sabadell.cat
      - LETSENCRYPT_HOST=guacamole.inabox.ies-sabadell.cat
    ports:
      - 8888:8080
    depends_on:
      postgres:
        condition: service_healthy
      guacd:
        condition: service_healthy
    networks:
      - backend

  inabox:
    container_name: www.${DOMAIN}
    image: gustaucastells/inabox
    restart: unless-stopped
    build:
      context: .
      dockerfile: services/inabox/Dockerfile
    environment:
      - DJANGO_DEBUG=False
      - VIRTUAL_HOST=www.inabox.ies-sabadell.cat
      - LETSENCRYPT_HOST=www.inabox.ies-sabadell.cat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - '8000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend

  static:
    container_name: static.${DOMAIN}
    image: gustaucastells/static
    restart: unless-stopped
    build:
      context: .
      dockerfile: services/static/Dockerfile
    environment:
      - PORT=80
      - SERVER_NAME=static.inabox.ies-sabadell.cat
      - SERVER_ROOT=/var/www/html
      - CONFIG_FILE=/etc/lighttpd/lighttpd.conf
      - SKIP_HEALTHCHECK=false
      - MAX_FDS=1024
      - VIRTUAL_HOST=static.inabox.ies-sabadell.cat
    expose:
      - '80'
    networks:
      - backend

volumes:
  db:
  html:
  slapd.d:
  vhost:

secrets:
  db-password:
    file: db-password.txt

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
