services:
  coredns:
    image: coredns/coredns
    container_name: 'dns.inabox.ies-sabadell.cat'
    restart: always
    expose:
      - '53'
      - '53/udp'
    ports:
      - '53:53'
      - '53:53/udp'
    volumes:
      - './services/coredns:/etc/coredns'
    command: -conf /etc/coredns/Corefile

  proxy:
    image: nginxproxy/nginx-proxy:1.4
    container_name: 'proxy.inabox.ies-sabadell.cat'
    restart: always
    environment:
      - TRUST_DOWNSTREAM_PROXY=true
      - ENABLE_IPV6=true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./services/nginx/certs:/etc/nginx/certs 
      - ./services/nginx/vhost:/etc/nginx/vhost.d
      - ./services/nginx/html:/usr/share/nginx/html
      - ./services/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      inabox:
        condition: service_started

#  proxy-acme:
#    image: nginxproxy/acme-companion
#    container_name: 'proxy-acme.inabox.ies-sabadell.cat'
#    restart: always
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ./services/nginx/certs:/etc/nginx/certs 
#      - ./services/nginx/vhost:/etc/nginx/vhost.d
#      - ./services/nginx/html:/usr/share/nginx/html
#      - ./services/nginx/acme:/etc/acme.sh
#    environment:
#      - "DEFAULT_EMAIL=inabox@ies-sabadell.cat"
#      - NGINX_PROXY_CONTAINER=proxy.inabox.ies-sabadell.cat
#    depends_on:
#      proxy:
#        condition: service_started

  ldap:
    image: osixia/openldap:1.5.0
    container_name: 'ldap.inabox.ies-sabadell.cat'
    restart: always
    environment:
      - LDAP_ORGANISATION=inabox
      - LDAP_DOMAIN=inabox.ies-sabadell.cat
      - "LDAP_BASE_DN=dc=inabox,dc=ies-sabadell,dc=cat"
      - LDAP_ADMIN_PASSWORD=inabox
    volumes:
      - ldap:/var/lib/ldap
      - slapd.d:/etc/ldap/slapd.d
    ports:
      - 389:389
      - 636:636

#  lam:
#    image: ghcr.io/ldapaccountmanager/lam:stable
#    container_name: 'lam.inabox.ies-sabadell.cat'
#    restart: always
#    environment:
#      - LDAP_DOMAIN=inabox.ies-sabadell.cat
#      - "LDAP_BASE_DN=dc=inabox,dc=ies-sabadell,dc=cat"
#      - LAM_PASSWORD=inabox
#      - LDAP_ORGANISATION='Inabox Institut Sabadell'
#      - LDAP_ADMIN_PASSWORD=inabox
#      - LDAP_READONLY_PASSWORD=inabox
#      - VIRTUAL_HOST=lam.inabox.ies-sabadell.cat
#      - VIRTUAL_PORT=80
#      - LETSENCRYPT_HOST=lam.inabox.ies-sabadell.cat
#    expose:
#      - '80'
#    depends_on:
#      ldap:
#        condition: service_started

  postgres:
    image: postgres
    container_name: 'postgres.inabox.ies-sabadell.cat'
    restart: always
    secrets:
      - db-password
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
       test: [ "CMD", "pg_isready" ]
       interval: 10s
       timeout: 5s
       retries: 5

#  adminer:
#    image: adminer
#    container_name: 'adminer.inabox.ies-sabadell.cat'
#    restart: always
#    environment:
#      - ADMINER_DEFAULT_SERVER=postgres
#      - ADMINER_DESIGN=nette
#      - VIRTUAL_HOST=adminer.inabox.ies-sabadell.cat
#      - VIRTUAL_PORT=8080
#      - LETSENCRYPT_HOST=adminer.inabox.ies-sabadell.cat      
#    expose:
#      - '8080'
#    depends_on:
#      postgres:
#        condition: service_healthy

  rabbitmq:
    image: rabbitmq
    container_name: 'rabbitmq.inabox.ies-sabadell.cat'
    ports:
      - '5672:5672'

  redis:
    image: redis:5
    container_name: 'redis.inabox.ies-sabadell.cat'
    restart: always
    ports:
      - '6379:6379'

#  guacd:
#    image: guacamole/guacd
#    container_name: 'guacd.inabox.ies-sabadell.cat'
#    restart: always
#    environment:
#      - GUACD_LOG_LEVEL=debug
#    ports:
#      - '4822:4822'

#  guacamole:
#    image: guacamole/guacamole
#    container_name: 'guacamole.inabox.ies-sabadell.cat'
#    restart: always
#    environment:
#      - POSTGRESQL_HOSTNAME=postgres
#      - POSTGRESQL_DATABASE=guacamole_db
#      - POSTGRESQL_USER=postgres
#      - POSTGRESQL_PASSWORD=development
#      - POSTGRESQL_PORT=5432
#      - GUACD_HOSTNAME=guacd
#      - GUACD_PORT=4822
#      - VIRTUAL_HOST=guacamole.inabox.ies-sabadell.cat
#      - LETSENCRYPT_HOST=guacamole.inabox.ies-sabadell.cat
#    expose:
#      - '8080'
#    depends_on:
#      postgres:
#        condition: service_healthy

  inabox:
    container_name: 'www.inabox.ies-sabadell.cat'
    build:
      context: .
    secrets:
      - django-secret-key
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_SECRET_KEY_FILE=/run/secrets/django-secret-key
      - VIRTUAL_HOST=www.inabox.ies-sabadell.cat
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=www.inabox.ies-sabadell.cat
    expose:
      - '8000'
    depends_on:
      postgres:
        condition: service_healthy
      ldap:
        condition: service_started
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started

volumes:
  db:
  html:
  ldap:
  slapd.d:
  vhost:

secrets:
  db-password:
    file: db-password.txt
  django-secret-key:
    file: django-secret-key.txt
