#!/bin/sh

rm -f app/migrations/*.py
rm -rf app/migrations/__pycache__

mv inabox.sqlite3 inabox.sqlite3.bak

python manage.py makemigrations challenges
python manage.py makemigrations
python manage.py migrate

python manage.py createsuperuser --username karasu --email notvalid@inabox.com 

python manage.py loaddata challenges/challenges

