#!/bin/sh

rm -f app/migrations/*.py
rm -rf app/migrations/__pycache__

mv inabox.sqlite3 inabox.sqlite3.bak

echo Running makemigrations step...
python manage.py makemigrations
python manage.py makemigrations app

echo Running migrate step...
python manage.py migrate

python manage.py createsuperuser --username karasu --email notvalid@inabox.com 

# Load fixtures into database
./loaddata

