#!/bin/sh

# start rabbitmq docker for switchboard
#docker rm -f inabox-rabbitmq
#docker run --name inabox-rabbit -p 5672:5672 -d rabbitmq

cd switchboard
./build_images
python switchboard.py
cd ..


