#!/bin/sh

# start rabbitmq docker for switchboard
#docker rm -f inabox-rabbitmq
#docker run --name inabox-rabbit -p 5672:5672 -d rabbitmq

cd docker-images
./build_images
cd ..

cd switchboard/docker-images
./build-images
cd ..
python switchboard.py
cd ..


