#!/bin/sh

echo "" > known_hosts

# start rabbitmq docker for switchboard and celery
docker rm -f inabox-rabbitmq
docker run --name inabox-rabbitmq -p 5672:5672 -d rabbitmq

# start redis docker for django-channels messaging
docker rm -f inabox-redis
docker run --name inabox-redis -p 6379:6379 -d redis:5

# Now run all services (development)
PWD=`pwd`
kitty --detach --title switchboard --directory $PWD ./run_switchboard
kitty --detach --title django --directory $PWD python manage.py runserver
kitty --detach --title celery --directory $PWD celery -A inabox worker --loglevel=INFO
