version: '3.1'

services:
  guacamole-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole
      POSTGRES_DB: guacamole_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - guacamole:/var/lib/postgresql/data
      - ./guacamole.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - backend

  guacd:
    image: guacamole/guacd
    restart: always
    environment:
      GUACD_LOG_LEVEL: debug
    ports:
      - 4822:4822
    networks:
      - backend

  guacamole:
    image: guacamole/guacamole
    restart: always
    environment:
      POSTGRESQL_HOSTNAME: guacamole-db
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USER: guacamole_user
      POSTGRESQL_PASSWORD: guacamole
      POSTGRESQL_PORT: 5432
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
    ports:
      - 8001:8080
    networks:
      - backend
      - frontend

volumes:
  guacamole:
  guacamole.sql:

networks:
  backend:
    driver: bridge
    internal: true
  frontend:
    driver: bridge

