#!/bin/sh

python manage.py makemigrations app && \
  python manage.py migrate && \
  python manage.py loaddata app/classgroups app/users app/challenges app/quests app/news && \
  /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
