# Generated by Django 4.2.7 on 2023-11-27 18:11

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ssh_port', models.IntegerField(default=30000, unique=True)),
                ('limit', models.IntegerField(default=30)),
                ('reuse', models.BooleanField(default=False)),
                ('ports', models.CharField(blank=True, default='', max_length=256)),
                ('volumes', models.TextField(blank=True, default='')),
                ('docker_file', models.FileField(upload_to=app.models.dockerimage_directory_path)),
                ('docker_image', models.FileField(blank=True, default='', upload_to=app.models.dockerimage_directory_path)),
                ('hash', models.CharField(default=app.models.createHash, max_length=128, unique=True)),
                ('image_id', models.CharField(default='0', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('full_name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('group', models.CharField(blank=True, default='', max_length=32)),
                ('role', models.CharField(choices=[('T', 'Teacher'), ('S', 'Student')], default='S', max_length=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=app.models.user_directory_path)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='DockerContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(default='0', max_length=128)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.challenge')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='docker_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dockerimage'),
        ),
    ]
