version: '3.1'
services:
  coredns:
    image: coredns/coredns
    container_name: 'dns.inabox.ies-sabadell.cat'
    restart: always
    expose:
      - '53'
      - '53/udp'
    ports:
      - '53:53'
      - '53:53/udp'
    volumes:
      - './coredns:/etc/coredns'
    command: -conf /etc/coredns/Corefile

  nginx:
    image: nginxproxy/nginx-proxy
    container_name: inabox1.inabox.ies-sabadell.cat
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - '80:80'
      - '443:443'

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap.inabox.ies-sabadell.cat
    restart: always
    environment:
      - LDAP_ORGANISATION=inabox
      - LDAP_DOMAIN=inabox.ies-sabadell.cat
      - LDAP_BASE_DN='dc=inabox,dc=ies-sabadell,dc=cat'
      - LDAP_ADMIN_PASSWORD=inabox
    ports:
      - 389:389
      - 636:636

  lam:
    image: ghcr.io/ldapaccountmanager/lam:stable
    container_name: lam.inabox.ies-sabadell.cat
    restart: always
    environment:
      - LDAP_DOMAIN=inabox.ies-sabadell.cat
      - LDAP_BASE_DN='dc=inabox,dc=ies-sabadell,dc=cat'
      - LAM_PASSWORD=inabox
      - LDAP_ORGANISATION='Inabox Institut Sabadell'
      - LDAP_ADMIN_PASSWORD=inabox
      - LDAP_READONLY_PASSWORD=inabox
      - VIRTUAL_HOST='lam.inabox.ies-sabadell.cat'
      - VIRTUAL_PORT=80
    expose:
      - '80'

  postgres:
    image: postgres
    container_name: postgres.inabox.ies-sabadell.cat
    restart: always
    environment:
      - POSTGRES_PASSWORD=development
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - inabox-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    container_name: adminer.inabox.ies-sabadell.cat
    restart: always
    environment:
      - VIRTUAL_HOST='adminer.inabox.ies-sabadell.cat'
      - VIRTUAL_PORT=80
    expose:
      - '8080'

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq.inabox.ies-sabadell.cat
    ports:
      - '5672:5672'

  redis:
    image: redis:5
    container_name: redis.inabox.ies-sabadell.cat
    restart: always
    ports:
      - '6379:6379'

  guacd:
    image: guacamole/guacd
    container_name: guacd.inabox.ies-sabadell.cat
    restart: always
    environment:
      - GUACD_LOG_LEVEL=debug
    ports:
      - '4822:4822'

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole.inabox.ies-sabadell.cat
    restart: always
    environment:
      - POSTGRESQL_HOSTNAME=postgres
      - POSTGRESQL_DATABASE=guacamole_db
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=development
      - POSTGRESQL_PORT=5432
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
      - VIRTUAL_HOST=guacamole.inabox.ies-sabadell.cat
      - VIRTUAL_PORT=80
    expose:
      - '8080'

volumes:
  inabox-db:
