version: '2'
services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
        - LDAP_ORGANISATION=inabox
        - LDAP_DOMAIN=inabox.ies-sabadell.cat
        - "LDAP_BASE_DN=dc=inabox,dc=ies-sabadell,dc=cat"
        - LDAP_ADMIN_PASSWORD=inabox
    ports:
        - 389:389
        - 636:636
  lam:
    image: ghcr.io/ldapaccountmanager/lam:stable
    container_name: lam
    ports:
      - 8003:80
